// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2016 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

// ------------------------ Functions -------------------------

// Address range: 0x80484b4 - 0x804859f
int main(int argc, char ** argv) {
    int32_t v1 = *(int32_t *)20; // 0x80484c0
    printf("Enter password: ");
    int32_t v2;
    scanf("%s", &v2);
    if (strlen("5tr0vZBrX:xTyR-P!") == 0) {
        // 0x8048569
        puts("\nSuccess!! Too easy.");
        // branch -> 0x804857a
        // 0x804857a
        if (*(int32_t *)20 != v1) {
            // 0x8048587
            __stack_chk_fail();
            // branch -> 0x804858c
        }
        // 0x804858c
        return 0;
    }
    int32_t v3 = 0;
    while (true) {
        unsigned char v4 = *(char *)(v3 + (int32_t)&v2); // 0x804851d
        int32_t v5 = v3 + 1; // 0x8048539
        if ((int32_t)v4 == (0x1000000 * v3 / 0x1000000 ^ 53)) {
            // 0x804853e
            if (v5 >= strlen("5tr0vZBrX:xTyR-P!")) {
                // break -> 0x8048569
                break;
            }
            v3 = v5;
            // continue -> 0x80484ff
            continue;
        } else {
            // 0x8048526
            puts("Wrong!");
            // branch -> 0x804857a
        }
        // 0x804857a
        if (*(int32_t *)20 != v1) {
            // 0x8048587
            __stack_chk_fail();
            // branch -> 0x804858c
        }
        // 0x804858c
        return 1;
    }
    // 0x8048569
    puts("\nSuccess!! Too easy.");
    // branch -> 0x804857a
    // 0x804857a
    if (*(int32_t *)20 != v1) {
        // 0x8048587
        __stack_chk_fail();
        // branch -> 0x804858c
    }
    // 0x804858c
    return 0;
}
